### ISSUE TITLE
MR for combined VTK packages

### ISSUE THREAD

**Issue by johnkit** [Kitware/pan3d#100]
UPdate VTK build/packing to detect X library and either 
* One linux, looks for glx then libegl then osmesa
* Windows opengl then osmesa

https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11367

**Comment by jspanchu** [comment]
I've spent some time getting the CI succeed since our meeting last week. Right now, there is only one job which fails for unrelated reasons. I'm waiting on another [MR](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11405) which removes an unnecessary unit test to merge. After that, we'll have to ask someone in the VTK space to review vtk/vtk#11367

**Comment by johnkit** [comment]
Currently merge conflict, but will request for reviewer

**Comment by johnkit** [comment]
Split off glad integration as separate MR (per Ben). Trying to keep up with VTK changes.

**Comment by johnkit** [comment]
MR merged yesterday (Sep16). Should get new pypi packages this weekend.
