### ISSUE TITLE
Create binder links for NASA and ESGF datasets 

### ISSUE THREAD

**Issue by aashish24** [Kitware/pan3d#134]
@aashish24 will provide the link to the NASA dataset and 2i2c binder instance that would allow stakeholders to launch our demos (dataset build, slice explorer, ESGF viewer)

**Comment by johnkit** [comment]
I've put some info for this issue in Kitware's internal pan3d Slack channel ([link](https://kitware.slack.com/archives/C03DX8B24TU/p1731363170298229)) to avoid publicly posting the binder URLs.

**Comment by aashish24** [comment]
NASA data of relevance  → IceSAT-2 (CryoCloud)

**Comment by aashish24** [comment]
- [ ] Create/share a binder link for the Pangeo data 
- [ ] Create/share a binder link for the ESGF data
- [ ] Create/share a binder link for the CryoCloud data

**Comment by johnkit** [comment]
# Pangeo Dataset

The binder links are posted in Kitware's internal Slack channel pan3d. The binder link for Pangeo data is disclosed in Slack message https://kitware.slack.com/archives/C03DX8B24TU/p1732302162815889

**Comment by johnkit** [comment]
# ESGF Dataset

The binder links are posted in Kitware's internal Slack channel pan3d. The binder link for ESGF data is disclosed in Slack message https://kitware.slack.com/archives/C03DX8B24TU/p1732302408322029

**Comment by johnkit** [comment]
# CryoCloud Dataset

There is no binder link for CryCloud data, because the data is stored in a repository that we want to keep internal (don't want to disclose in a public jupyter notebook). There is, however, a pan3d config file for loading the dataset into the pan3d `xr-viewer`. That config file is attached to https://kitware.slack.com/archives/C03DX8B24TU/p1732045659830899
